/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BarChart: typeof import('./components/mine/barChart.vue')['default']
    Chat: typeof import('./components/ai/chat.vue')['default']
    EtcmList: typeof import('./components/item/etcmList.vue')['default']
    Graph: typeof import('./components/item/graph.vue')['default']
    Info: typeof import('./components/item/info.vue')['default']
    PieChart: typeof import('./components/mine/pieChart.vue')['default']
    RadarChart: typeof import('./components/mine/radarChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RuleGraph: typeof import('./components/mine/ruleGraph.vue')['default']
    SearchAns: typeof import('./components/search/search-ans.vue')['default']
    SearchLoading: typeof import('./components/search/search-loading.vue')['default']
    SearchMain: typeof import('./components/search/search-main.vue')['default']
    Thought: typeof import('./components/ai/thought.vue')['default']
    Thought_finish: typeof import('./components/ai/thought_finish.vue')['default']
    Thought_loading: typeof import('./components/ai/thought_loading.vue')['default']
  }
}
