/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchAns: typeof import('./components/search/search-ans.vue')['default']
    SearchLoading: typeof import('./components/search/search-loading.vue')['default']
    SearchMain: typeof import('./components/search/search-main.vue')['default']
  }
}
